from .flask_compress import Compress

# _version.py is generated by setuptools_scm when building the package.
# It is not version-controlled, so if it is missing, this likely means that
# the imported code was installed from the git repo without using "editable" mode.
try:
    from ._version import __version__
except ImportError:
    __version__ = "0"


__all__ = ("Compress",)
